config/routes.rb
Rails.application.routes.draw do
  
  constraints(:host => /www.bitnotes.in/) do
    match "/(*path)" => redirect {|params, req| "http://bitnotes.in/#{params[:path]}"},  via: [:get, :post]
  end
  constraints(:host => /bitnotes.tk/) do
    match "/(*path)" => redirect {|params, req| "http://bitnotes.in/#{params[:path]}"},  via: [:get, :post]
  end
/ Root path /
 root "abouts#index"

  get '/privacy'=>'abouts#privacy',as:"privacy"
  get '/about'=>'abouts#about', as: "about"
  get '/terms'=>'abouts#terms', as:"terms"
  get '/creators'=>'abouts#creators', as:"creators"
  get '/copyright'=>'abouts#copyright', as:"copyright"
  get '/try'=>'abouts#try', as:"try"
  get '/lang'=>'abouts#language',as:"language"
  get '/team'=>'abouts#team',as:"team"
  get '/result'=>'abouts#result',as:"result"
  get '/spams/add'=>'spams#add',as:'add_spam'
  get 'practicals/:id/destroyimage'=>"practicals#destroyimage",as:"destroypimage"
  get 'assignments/:id/destroyimage'=>"assignments#destroyimage",as:"destroyaimage"
  get 'colleges/:id/destroyimage'=>"colleges#destroyimage",as:"destroycimage"
  get 'qpapers/:id/destroyimage'=>"qpapers#destroyimage",as:"destroyqimage"
  get 'examnotes/:id/destroyimage'=>"examnotes#destroyimage",as:"destroyeimage"
  get 'subjects/:id/destroyimage'=>"subjects#destroyimage",as:"destroysimage"
  get 'users/:id/dashboard'=>"users#dashboard",as:"user_dashboard"
  get 'users/:id/dashboard/assignments'=>"users#dashassignments",as:"user_dashboard_assignments"
  get 'users/:id/dashboard/examnotes'=>"users#dashexamnotes",as:"user_dashboard_examnotes"
  get 'users/:id/dashboard/qpapers'=>"users#dashqpapers",as:"user_dashboard_qpapers"
  get 'users/:id/dashboard/subjects'=>"users#dashsubjects",as:"user_dashboard_subjects"
  get 'users/:id/dashboard/colleges'=>"users#dashcolleges",as:"user_dashboard_colleges"
  get 'loadmorepracticals'=>'practicals#loadmore',as:"loadmorepracticals"
  get 'loadmoreassignments'=>'assignments#loadmore',as:"loadmoreassignments"
  get 'loadmoreexamnotes'=>'examnotes#loadmore',as:"loadmoreexamnotes"
  get 'loadmoreqpapers'=>'qpapers#loadmore',as:"loadmoreqpapers"
  get 'loadmoresubjects'=>'subjects#loadmore',as:"loadmoresubjects"
  get 'loadmorecolleges'=>'colleges#loadmore',as:"loadmorecolleges"

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  resources :sessions, only: [:create, :destroy]

/ Resources /

  resources :users
  resources :relationships, only:[:create,:destroy]

  resources :abouts
  
  resources :practicals do
    member do
      put "like"=>"practicals#upvote"
      put "dislike"=>"practicals#downvote"
    end
  end
  resources :assignments do
    member do
      put "like"=>"assignments#upvote"
      put "dislike"=>"assignments#downvote"
    end
  end
  resources :examnotes do
    member do
      put "like"=>"examnotes#upvote"
      put "dislike"=>"examnotes#downvote"
    end
  end
  resources :qpapers do
    member do
      put "like"=>"qpapers#upvote"
      put "dislike"=>"qpapers#downvote"
    end
  end
  resources :subjects do
    member do
      put "like"=>"subjects#upvote"
      put "dislike"=>"subjects#downvote"
    end
  end
  resources :colleges do
    member do
      put "like"=>"colleges#upvote"
      put "dislike"=>"colleges#downvote"
    end
  end
  resources :requests do
    member do
      put "like"=>"requests#upvote"
    end
  end


  namespace :v1 do
    resources :practicals do
      member do
        put "like"=>"practicals#upvote"
        put "dislike"=>"practicals#downvote"
      end
    end
    resources :assignments do
      member do
        put "like"=>"assignments#upvote"
        put "dislike"=>"assignments#downvote"
      end
    end
    resources :colleges do
      member do
        put "like"=>"practicals#upvote"
        put "dislike"=>"practicals#downvote"
      end
    end
    resources :examnotes do
      member do
        put "like"=>"examnotes#upvote"
        put "dislike"=>"examnotes#downvote"
      end
    end
    resources :qpapers do
      member do
        put "like"=>"qpapers#upvote"
        put "dislike"=>"qpapers#downvote"
      end
    end
    resources :subjects do
      member do
        put "like"=>"subjects#upvote"
        put "dislike"=>"subjects#downvote"
      end
    end
    resources :users,only: [:show]
    resources :abouts,only: [:index]
    get '/result'=>'abouts#result',as:"result"
    post '/users/user_oauth' => 'users/user_oauth',as: "user_oauth"
  end

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
	is_impressionable :counter_cache => true, :column_name => :views, :unique => :all
	searchkick
	acts_as_votable
	belongs_to :user
	belongs_to :college
	belongs_to :subject
	has_many :aimages
	accepts_nested_attributes_for :aimages, reject_if: :all_blank, allow_destroy: true

	scope :recent,->{all.order("created_at DESC")}


	validates :topic, presence: true,length:{minimum: 5}
	validates :college_id, presence: true
	validates :subject_id, presence: true
	validates :description, presence: true, length:{minimum: 20}
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
	
	impressionist actions: [:show]
	before_action :get_assignment,only: [:show,:edit,:update,:destroy,:upvote,:downvote,:destroyimage]
	before_action :authenticate_user!,only:[:edit,:new,:create,:update,:destroy]

	def index
		@assignmentpageindex = 1
		if current_user && current_user.college_id.present?
			@rassignments = Assignment.where(college_id: current_user.college_id).order("created_at DESC").limit(12)
			@recentAssignments = Assignment.where.not(college_id: current_user.college_id).order("created_at DESC").limit(4)
		else	
			@recentAssignments = Assignment.recent.paginate(page: 1,per_page: 8)
		end
	end

	def show
		@recentAssignments = Assignment.recent.limit(4)
		@recentPracticals = Practical.recent.limit(4)
		@recentQpapers = Qpaper.recent.limit(4)
		@recentExamnotes = Examnote.recent.limit(4)
	end

	def new
		@assignment = Assignment.new
		render layout: "form"
	end

	def create
		@assignment = Assignment.new(assignment_params)
		@assignment.user_id = current_user.id
		if @assignment.save
			redirect_to @assignment,notice:"Successfully created your Assignment."
		else
			render layout: "form",action:"new"
		end
	end

	def edit
		if session[:user_id] == @assignment.user_id
			@check = 1
			render layout: "form"
		else
			redirect_to root_path,notice:"Gotcha!, You don't have access to edit this Assignment."
		end
	end

	def update
		if session[:user_id] = @assignment.user_id
			if @assignment.update(assignment_params)
				redirect_to @assignment,notice:"Successfully updated your Assignment."
			else
				render layout: "form",action:"edit"
			end
		else
			redirect_to root_path,notice:"Gotcha!, You don't have access to update this Assignment."
		end
		
	end

	def destroy
		if session[:user_id] == @assignment.user_id
			@assignment.destroy
			redirect_to root_path,notice:"Destroyed your Assignment."
		else
			redirect_to root_path,notice:"Gotcha!, You don't have rights to Delete this Assignment"
		end
	end

	def upvote
		@assignment.upvote_by current_user
		@flag = 0 unless current_user
		respond_to do |format|
			format.html{redirect_to :back}
			format.js
		end
	end
	def downvote
		@assignment.downvote_by current_user
		@flag = 0 unless current_user
		respond_to do |format|
			format.html{redirect_to :back}
			format.js
		end
	end


	def destroyimage
		@aimage = @assignment.aimages.find(params[:imageid])
		@aimage.destroy
		redirect_to :back
	end

	def loadmore
		@assignments = Assignment.all.order("created_at DESC").paginate(page: params[:page],per_page: 4)
		@assignmentpageindex = params[:page].to_i
		respond_to do |format|
			format.html{redirect_to :back}
			format.js
		end
	end
	private
		def get_assignment
			@assignment = Assignment.find(params[:id])
		end

		def assignment_params
			params.require(:assignment).permit(:topic,:description,:college_id,:subject_id,aimages_attributes: [:id,:image,:_destroy])
		end
end

app/controllers/v1/assignments_controller.rb
module V1
	class AssignmentsController < ApiController
		before_action :get_assignment, only:[:show,:upvote,:downvote]
		before_action :get_current_user,only:[:upvote,:downvote]
		skip_before_filter :verify_authenticity_token
		
		def index
			@assignments = Assignment.recent.limit(12)
			render json: @assignments.as_json(include: { user: { only: [:phname] }, aimages: { methods: [:image_url], only: [] } }), status: :ok
		end


		def show
			render json: @assignment.as_json(include: { user: { only: [:phname] }, aimages: { methods: [:image_url], only: [] } }), status: :ok
		end

		def upvote
			@assignment.upvote_by current_user
			render status: :ok, json:{
				votes: @assignment.cached_votes_up
			}
		end

		def downvote
			@assignment.downvote_by current_user
			render status: :ok, json:{
				votes: @assignment.cached_votes_up
			}
		end

		private

			def get_assignment
				@assignment = Assignment.find(params[:id])
			end

			def get_current_user
				current_user = User.find(params[:user_id])
			end
	end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
    /**
     *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
     *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
     */
    var disqus_config = function () {
        shortname = "Bitnotes"
        this.page.url = '<%= url_for([@assignment,{only_path: false}]) %>';  // Replace PAGE_URL with your page's canonical URL variable
        this.page.identifier = <%= "assignments/#{@assignment.id}"%>; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };

    (function() {  // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        
        s.src = '//bitnotes.disqus.com/embed.js';
        
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/assignments/_fbshare.html.erb
<script>
document.getElementById('shareBtn').onclick = function() {
  FB.ui({
    method: 'share',
    display: 'popup',
    href: '<%= url_for([@assignment,{only_path: false} ]) %>',
  }, function(response){});
}
</script>

app/views/assignments/_form.html.erb
<div class='form-container'>
	<%= simple_form_for(@assignment,html:{multipart: true}) do |f|%>

		<div class='form-item'>
			<div class='data-header'>
				<span class='header-name'>Topic:</span>
			</div>
			<div class='form-data'>
				<%= f.input :topic,label: false,placeholder:"What is your Assignment About?"%>	
			</div>
		</div>
		<div class='form-item'>
			<div class='data-header'>
				<span class='header-name'>Subject:</span>
				<span class="header-tip">If Subject not Found,add Subject <%= link_to "here",new_subject_path %></span>
			</div>
			<div class='form-data'>
				<%=f.input :subject_id,collection: Subject.all.order("name ASC"),prompt: "Choose Subject of Assignment",label:false	%>
			</div>
		</div>
		<div class='form-item'>
			<div class='data-header'>
				<span class='header-name'>College:</span>
				<span class='header-tip'>If Institute not Found,add Your Institute <%=link_to "here",new_college_path %></span>
			</div>
			<div class='form-data'>
				<%=f.input :college_id,collection: College.all.order("name ASC"),label:"Institute",prompt:"Choose Institute related to Assignment",label: false	%>
			</div>
		</div>
		<div class='form-item'>
			<div class='data-header'>
				<span class='header-name'>Description:</span>
				<span class='header-tip'>Describe above Assignment</span>
			</div>
			<div class='form-data'>
				<%=f.input :description, label: false, placeholder:"Describe your assignment"	%>
			</div>
		</div>
		<div class='form-item'>
			<div class='form-data'>
				<div id='image-preview-box'>	
				<% if @check == 1 %>
					<% if @assignment.aimages.count > 0%>
					
						<% @assignment.aimages.each do |aimage| %>

							<div class="image-preview" style="background: url(<%=aimage.image.url(:small) %>) no-repeat; background-size: 150px 200px;  ">
								<!--  Ajax call and Jquery remove function for destroyimage_path -->
								<%= link_to destroyaimage_path(id: @assignment.id,imageid: aimage.id),remote: true do%>
										<span class="delete-image">
											<svg fill="#0288d1" height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg">					    <path d="M15 16h4v2h-4zm0-8h7v2h-7zm0 4h6v2h-6zM3 18c0 1.1.9 2 2 2h6c1.1 0 2-.9 2-2V8H3v10zM14 5h-3l-1-1H6L5 5H2v2h12z"></path><path d="M0 0h24v24H0z" fill="none"></path>					
											</svg>
										</span>
								<% end %>
								

								<input type="file" name="assignment[aimages_attributes][<%= aimage.id %>][image]" style="display: none">
							</div>
				
						<% end%>
					<% end %>							
				<% end %>
				</div>
			</div>
			<div class='data-header'>
				<span id='add-image' onclick='addImage("assignment","aimages")' title="Add Image">
					<svg fill="#2196F3" height="48" viewBox="0 0 24 24" width="48" xmlns="http://www.w3.org/2000/svg">
					    <circle cx="12" cy="12" r="3.2"/>
					    <path d="M9 2L7.17 4H4c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2h-3.17L15 2H9zm3 15c-2.76 0-5-2.24-5-5s2.24-5 5-5 5 2.24 5 5-2.24 5-5 5z"/>
					    <path d="M0 0h24v24H0z" fill="none"/>
					</svg>
				</span>
			</div>

		</div>
		<div class='form-actions'>
			<%=f.submit class:"btn btn-primary form-actions-btn form-submit" %>
			<%= link_to :back do %>  
				<span class="btn btn-primary form-actions-btn form-cancel">Cancel</span>
			<% end %>
		</div>
		
	<% end %>
</div>


app/views/assignments/downvote.js.erb
var alert = $('<div class="alert alert-warning alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><h4>Sign In before you like the Post</h4></div>');
<% if @flag == 0 %>
	$(".show-top-grids").prepend(alert);
<% else %>
	$("#dislikebtn").hide();
	$("#likebtn").fadeIn();
	$("#likebtn").find(".likecount").text(<%= @assignment.get_upvotes.size %>);
<% end %>

app/views/assignments/edit.html.erb
<% title "Edit Assignment" %>
<div class="upload">
	<!-- container -->
	<div class="container">
		<div class="upload-grids">
			<div>
				<% if @assignment.errors.any? %>
					<div class="alert alert-danger alert-dismissible" role="alert">
					   	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true	">&times;</span></button>
						<h2><%= pluralize(@assignment.errors.count, "Error")%> prevented this assignment from saving</h2>
						<ul>
							<% @assignment.errors.full_messages.each do |msg| %>
								<li><%= msg%></li>
							<% end%>
						</ul>
					</div>
				<% end %>	
			</div>			

			<%= render "form" %>
		
			<%= render "shared/help" %>
		</div>
	</div>
	<!-- //container -->
</div>

app/views/assignments/index.html.erb
<% title "Trending Assignment" %>
<% keywords "Assignments, Free, BitNotes, Education, Sharing, Caring, Earn, Learn" %>
<% description " Free Trending Assignments from BitNotes" %>
<% author "BitNotes"%>
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
	<div class="main-grids">
		<div class="recommended">
			<div class="recommended-grids">
				<%=  render "shared/adsense" %>
	<% if current_user && current_user.college_id.present? %>
				<div class="recommended-info">
					<h3>Recommended</h3>
				</div>
				<% @rassignments.each do |assignment| %>
					<%= render partial:"shared/assignment",locals:{assignment: assignment} %>
				<% end %>
				<div class="clearfix"> </div>
			</div>
		</div>
		<hr>
		<div class="recommended">
			<div class="recommended-grids">

	<% end %>
                <div class="recommended-info">
					<h3>Assignments</h3>
				</div>
				<% @recentAssignments.each do |assignment| %>
					<%= render partial: "shared/assignment",locals:{assignment: assignment} %>
				<% end %>
				<div class="clearfix"> </div>
			</div>
		</div>
		<div class="loadmoreassignmentdiv">
			<%= link_to "Load More",loadmoreassignments_path(page: @assignmentpageindex + 1),remote: true,class:"loadmorebtn" %>
		</div>
	</div>
	<%= render "shared/advfooter" %>

app/views/assignments/loadmore.js.erb
$(document).ready(function(){
	<% unless @assignments.empty? %>
		// var assignments = $('<div class="recommended"><div class="recommended-grids"><% @assignments.each do |assignment| %><div class="col-md-3 resent-grid recommended-grid"><div class="resent-grid-img recommended-grid-img"><% if assignment.aimages.count > 0 %><%= link_to image_tag(assignment.aimages.first.image.url(:small),alt: assignment.topic),assignment %><%else %><%= link_to image_tag("defaultcoverimage",alt: assignment.topic),assignment %><% end %><div class="time small-time" title="Pages Count"><p><%= assignment.aimages.count %></p></div><div class="clck small-clck" title="Pages"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span></div></div><div class="resent-grid-info recommended-grid-info video-info-grid"><h5><%= link_to assignment.topic,assignment,class:"title", title: assignment.topic%><br></h5><small>Submitted <strong> <%=time_ago_in_words(assignment.created_at) %> ago</strong></small><ul><li><p class="author author-info"><%= link_to assignment.user.phname,  controller:"users",action:"show",id:assignment.user_id,class:"author"%></p></li><li class="right-list"><p class="views views-info"><strong><%=assignment.views %></strong> views</p></li></ul></div></div><% end %><div class="clearfix"> </div></div></div>');
		var assignments = $('<div class="recommended"><div class="recommended-grids"><% @assignments.each do |assignment| %>'+'<%=j render partial: "shared/assignment", locals:{assignment: assignment} %>'+'<% end %><div class="clearfix"> </div></div></div>');
		$('.loadmoreassignmentdiv').before(assignments).fadeIn();
		$('.loadmoreassignmentdiv').find('a').replaceWith('<%= link_to "Load More",loadmoreassignments_path(page: @assignmentpageindex+1),remote: true,class:"loadmorebtn" %>');
	<% end %>
});

app/views/assignments/new.html.erb
<% title "New Assignment" %>
<div class="upload">
	<!-- container -->
	<div class="container">
		<div class="upload-grids">
			<div>
				<% if @assignment.errors.any? %>
					<div class="alert alert-danger alert-dismissible" role="alert">
					   	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true	">&times;</span></button>
						<h2><%= pluralize(@assignment.errors.count, "Error")%> prevented this assignment from saving</h2>
						<ul>
							<% @assignment.errors.full_messages.each do |msg| %>
								<li><%= msg%></li>
							<% end%>
						</ul>
					</div>
				<% end %>	
			</div>			

			<%= render "form" %>
		
			<%= render "shared/help" %>
		</div>
	</div>
	<!-- //container -->
</div>

app/views/assignments/show.html.erb
<% title @assignment.topic %>
<% keywords "#{@assignment.topic}, #{@assignment.user.phname},Assignments,Exams, BitNotes, Share, Care, Learn, Earn" %>
<% description "#{@assignment.topic} is assignment of #{@assignment.user.phname} publication" %>
<% author "#{@assignment.user.phname}" %>
<% fbsharetitle "#{@assignment.topic}" %>
<% fbshareurl "#{url_for([@assignment,{only_path: false}])}" %>
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
	<div class="show-top-grids">
		<% if flash.any? %>
			<div class="alert alert-success alert-dismissible" role="alert">
			   	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true	">&times;</span></button>
			   	<h4><%= flash[:notice]%></h4>
			</div>
		<% end %>
		<div class="col-sm-8 single-left">
			<%= render "shared/adsense" %>
			<br>
			<div class="song">
				<div class="song-info">
					<h3 title="Assignment Topic"><%= @assignment.topic %></h3>	
				</div>
				<div class="video-grid">
					<ul class="docs-pictures">
						<% if @assignment.aimages.count > 0 %>
							<% fbshareimage "#{ @assignment.aimages.first.image.url(:thumb) }" %>
							<% @assignment.aimages.each do |aimage| %>
								<li><%=image_tag(aimage.image.url(:medium),alt: @assignment.topic,class: "img-thumbnail",height:"140px",width:"140px",data:{original: aimage.image.url(:thumb)}) %></li>
							<% end %>
						<% end %>
					</ul>
				</div>
			</div>
			<div class="clearfix"> </div>

			<% @user = User.find(@assignment.user_id) %>


			<div class="show-right-grids">
				<ul>
					<li>
						<% if @user.avatar.url == "/avatars/original/missing.png" %>
		                	<%= link_to image_tag("customprofile",alt:"logo",height: "50px"),controller:"users",action:"show",id:@user.id %> 
		                <%else%>
		                	<%= link_to image_tag(@user.avatar.url(:thumb),alt:"logo",height: "50px",alt:@user.phname),controller: "users",action:"show",id:@user.id %>
		                <% end %>

					</li>
					<li><%=link_to @assignment.user.phname,controller:"users",action: "show",id: @assignment.user_id%><br>
					<%= render partial:'shared/subscribe_form',locals:{fi: 0} if current_user %></li></li>
                    <br>
				</ul>
			</div>
			<div class="social_response">
				<ul>
					<li><a href="#" class="icon fb-icon" title="Share on Facebook" id="shareBtn">Facebook</a></li>
					<li><a href="https://plus.google.com/share?url={<%= url_for([@assignment,{only_path: false}]) %>}" onclick="javascript:window.open(this.href,
  			'', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;" class="icon googleplus-icon" title="Share on Google Plus"></a></li>
					<li><a href="//www.reddit.com/submit" target="_blank" class="icon reddit-icon" title="Share on Reddit" onclick="window.location = '//www.reddit.com/submit?url=' + encodeURIComponent(window.location); return false"></a></li>
					<li><a href="https://twitter.com/intent/tweet?text= <%= "Check this "+ @assignment.topic + " " + url_for([@assignment,{only_path: false}])%>" target="_blank" title="Share on Twitter" class="icon twitter-icon">Twitter</a></li>
					<li>
						<% if current_user %>
							<%= link_to dislike_assignment_path(@assignment),method: :put,class:"icon dislike",title:"Dislike this",id:"dislikebtn",style:"display:#{"none" unless current_user.liked?@assignment}",remote: true do %>
								<span class="dislikecount"><strong><%= @assignment.cached_votes_up %></strong></span>	
							<% end %>
							<%= link_to like_assignment_path(@assignment),method: :put,class:"icon like",title:"Like this", id:"likebtn",style:"display:#{"none" if current_user.liked?@assignment}",remote: true do %>
								<span class="likecount"><strong><%= @assignment.cached_votes_up %></strong></span>
							<% end %>
						<% else %>
							<%= link_to like_assignment_path(@assignment),method: :put,class:"icon like",title:"Like this", id:"likebtn",remote: true do %>
							<span class="likecount"><strong><%= @assignment.cached_votes_up %></strong></span>
							<% end %>
						<%end %>
					</li>
					<li class="view" title="Views Count"><strong><%= @assignment.views %> views</strong></li>
					<% if session[:user_id] && session[:user_id] == @assignment.user_id %>
						<li><%=link_to "Edit",edit_assignment_path(@assignment),id:"edit_profile_btn" %></li>
						<li><%=link_to "Delete",@assignment,method: :delete,data:{confirm:"Are you sure?"},id:"edit_profile_btn" %></li>
					<% end %>
					<% if current_user %>
						<li><%= link_to "Mark as Spam",add_spam_path(user_id: current_user.id,post_id: @assignment.id,type_id: 3),id: "edit_profile_btn" %></li>
					<% end %>
				</ul>
				<%= render "fbshare" %>
			</div>
			<div class="clearfix"> </div>
			<div class="published">
				<div class="load_more">	
					<ul id="myList">
						<li>
							<h4>Published on <%= @assignment.created_at.strftime("%d %B %Y") %></h4>
							<p><%= simple_format(@assignment.description.slice(0..30))  %>
						</li>
						<li>
							<%= simple_format(@assignment.description.slice(30..-1)) %></p>
							<div class="load-grids">
								<div class="load-grid-info">
									<p>Category:</p>
									<p>College:</p>
									<p>Subject:</p>
								</div>
								<div class="load-grid">
									<p><%= link_to "Assignment",assignments_path %></p>
									<p><%= link_to @assignment.college.name,controller:"colleges",action:"show",
									id: @assignment.college_id %></p>
									<p><%= link_to @assignment.subject.name,controller:"subjects",action:"show",id: @assignment.subject_id%></p>
								</div>
								<div class="clearfix"> </div>
							</div>
						</li>
					</ul>
					<button id="loadMore" title="See more details">Load more</button>
					<button id="showLess" style="display:none" title="See less details">Show less</button>
				</div>
			</div>
			<div class="all-comments">
				<div class="all-comments-info">
					<%= render "disqus" %>
				</div>
			</div>

			<br>
			<%= render "shared/advfooter" %>
			<br>
		</div>
		<div class="col-md-4 single-right">
			<div class="single-grid-right">
				<div class="single-right-grids">
					<div class="col-md-12 single-right-grid-left" style="margin: 0; padding: 0;">
						<%= render("shared/adv") %>
					</div>
				</div>
			</div>
			<h3>Up Next</h3>
			<div class="single-grid-right">
				<% @recentQpapers.each do |qpaper| %>
					<%= render partial: "shared/qpapersuggestion",locals:{qpaper: qpaper} %>
				<% end %>
				<% @recentAssignments.each do |assignment| %>
					<%= render partial:"shared/assignmentsuggestion",locals:{assignment: assignment} %>
				<% end %>
				<% @recentPracticals.each do |practical| %>
					<%= render partial: "shared/practicalsuggestion",locals:{practical: practical} %>
				<% end %>
				<% @recentExamnotes.each do |examnote| %>
					<%= render partial: "shared/examnotesuggestion",locals:{examnote: examnote} %>
				<% end %>
			</div>
		</div>
		<div class="clearfix"> </div>
	</div>

app/views/assignments/upvote.js.erb
var alert = $('<div class="alert alert-warning alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><h4>Sign In before you like the Post</h4></div>');
<% if @flag == 0 %>
	$(".show-top-grids").prepend(alert);
<% else %>
	$("#likebtn").hide();
	$("#dislikebtn").fadeIn();
	$("#dislikebtn").find(".dislikecount").text(<%= @assignment.get_upvotes.size %>);
<% end %>