config/routes.rb
Rails.application.routes.draw do
  
  constraints(:host => /www.bitnotes.in/) do
    match "/(*path)" => redirect {|params, req| "http://bitnotes.in/#{params[:path]}"},  via: [:get, :post]
  end
  constraints(:host => /bitnotes.tk/) do
    match "/(*path)" => redirect {|params, req| "http://bitnotes.in/#{params[:path]}"},  via: [:get, :post]
  end
/ Root path /
 root "abouts#index"

  get '/privacy'=>'abouts#privacy',as:"privacy"
  get '/about'=>'abouts#about', as: "about"
  get '/terms'=>'abouts#terms', as:"terms"
  get '/creators'=>'abouts#creators', as:"creators"
  get '/copyright'=>'abouts#copyright', as:"copyright"
  get '/try'=>'abouts#try', as:"try"
  get '/lang'=>'abouts#language',as:"language"
  get '/team'=>'abouts#team',as:"team"
  get '/result'=>'abouts#result',as:"result"
  get '/spams/add'=>'spams#add',as:'add_spam'
  get 'practicals/:id/destroyimage'=>"practicals#destroyimage",as:"destroypimage"
  get 'assignments/:id/destroyimage'=>"assignments#destroyimage",as:"destroyaimage"
  get 'colleges/:id/destroyimage'=>"colleges#destroyimage",as:"destroycimage"
  get 'qpapers/:id/destroyimage'=>"qpapers#destroyimage",as:"destroyqimage"
  get 'examnotes/:id/destroyimage'=>"examnotes#destroyimage",as:"destroyeimage"
  get 'subjects/:id/destroyimage'=>"subjects#destroyimage",as:"destroysimage"
  get 'users/:id/dashboard'=>"users#dashboard",as:"user_dashboard"
  get 'users/:id/dashboard/assignments'=>"users#dashassignments",as:"user_dashboard_assignments"
  get 'users/:id/dashboard/examnotes'=>"users#dashexamnotes",as:"user_dashboard_examnotes"
  get 'users/:id/dashboard/qpapers'=>"users#dashqpapers",as:"user_dashboard_qpapers"
  get 'users/:id/dashboard/subjects'=>"users#dashsubjects",as:"user_dashboard_subjects"
  get 'users/:id/dashboard/colleges'=>"users#dashcolleges",as:"user_dashboard_colleges"
  get 'loadmorepracticals'=>'practicals#loadmore',as:"loadmorepracticals"
  get 'loadmoreassignments'=>'assignments#loadmore',as:"loadmoreassignments"
  get 'loadmoreexamnotes'=>'examnotes#loadmore',as:"loadmoreexamnotes"
  get 'loadmoreqpapers'=>'qpapers#loadmore',as:"loadmoreqpapers"
  get 'loadmoresubjects'=>'subjects#loadmore',as:"loadmoresubjects"
  get 'loadmorecolleges'=>'colleges#loadmore',as:"loadmorecolleges"

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  resources :sessions, only: [:create, :destroy]

/ Resources /

  resources :users
  resources :relationships, only:[:create,:destroy]

  resources :abouts
  
  resources :practicals do
    member do
      put "like"=>"practicals#upvote"
      put "dislike"=>"practicals#downvote"
    end
  end
  resources :assignments do
    member do
      put "like"=>"assignments#upvote"
      put "dislike"=>"assignments#downvote"
    end
  end
  resources :examnotes do
    member do
      put "like"=>"examnotes#upvote"
      put "dislike"=>"examnotes#downvote"
    end
  end
  resources :qpapers do
    member do
      put "like"=>"qpapers#upvote"
      put "dislike"=>"qpapers#downvote"
    end
  end
  resources :subjects do
    member do
      put "like"=>"subjects#upvote"
      put "dislike"=>"subjects#downvote"
    end
  end
  resources :colleges do
    member do
      put "like"=>"colleges#upvote"
      put "dislike"=>"colleges#downvote"
    end
  end
  resources :requests do
    member do
      put "like"=>"requests#upvote"
    end
  end


  namespace :v1 do
    resources :practicals do
      member do
        put "like"=>"practicals#upvote"
        put "dislike"=>"practicals#downvote"
      end
    end
    resources :assignments do
      member do
        put "like"=>"assignments#upvote"
        put "dislike"=>"assignments#downvote"
      end
    end
    resources :colleges do
      member do
        put "like"=>"practicals#upvote"
        put "dislike"=>"practicals#downvote"
      end
    end
    resources :examnotes do
      member do
        put "like"=>"examnotes#upvote"
        put "dislike"=>"examnotes#downvote"
      end
    end
    resources :qpapers do
      member do
        put "like"=>"qpapers#upvote"
        put "dislike"=>"qpapers#downvote"
      end
    end
    resources :subjects do
      member do
        put "like"=>"subjects#upvote"
        put "dislike"=>"subjects#downvote"
      end
    end
    resources :users,only: [:show]
    resources :abouts,only: [:index]
    get '/result'=>'abouts#result',as:"result"
    post '/users/user_oauth' => 'users/user_oauth',as: "user_oauth"
  end

end

app/views/shared/_assignment.html.erb
<div class="col-md-3 resent-grid recommended-grid">
	<div class="resent-grid-img recommended-grid-img">
	<% if assignment.aimages.count > 0 %>
		<%= link_to image_tag(assignment.aimages.first.image.url(:small),alt: assignment.topic),assignment %>
	<%else %>
		<%= link_to image_tag("defaultcoverimage",alt: assignment.topic),assignment %>
	<% end %>
		<div class="time small-time" title="Pages Count">
			<p><%= assignment.aimages.count %></p>
		</div>
		<div class="clck small-clck" title="Pages">
			<span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>
		</div>
	</div>
	<div class="resent-grid-info recommended-grid-info video-info-grid">
		<h5><%= link_to assignment.topic,assignment,class:"title", title: assignment.topic%><br></h5>
		<small>Submitted <strong> <%=time_ago_in_words(assignment.created_at) %> ago</strong></small>
		<ul>
			<li><p class="author author-info"><%= link_to assignment.user.phname,  controller:"users",action:"show",id:assignment.user_id,class:"author"%></p></li>
			<li class="right-list"><p class="views views-info"><strong><%=assignment.views %></strong> views</p></li>
		</ul>
	</div>
</div>

app/views/shared/_college.html.erb
<div class="col-md-3 resent-grid recommended-grid">
	<div class="resent-grid-img recommended-grid-img">
	<% if college.cimages.count > 0 %>
		<%= link_to image_tag(college.cimages.first.image.url(:small),alt: college.name),college %>
	<%else%>
		<%= link_to image_tag("defaultcoverimage",alt: college.name),college %>
	<% end %>
		<div class="time small-time" title="Pages Count">
			<p><%= college.cimages.count %></p>
		</div>
		<div class="clck small-clck" title="Pages">
			<span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>
		</div>
	</div>
	<div class="resent-grid-info recommended-grid-info video-info-grid">
		<h5><%=link_to college.name,college, class:"title" %><br></h5>
		<small>Submitted <strong> <%=time_ago_in_words(college.created_at) %> ago</strong></small>
		<ul>
			<li><p class="author author-info"><%= link_to college.user.phname,  controller:"users",action:"show",id:college.user_id,class:"author"%></p></li>
			<li class="right-list"><p class="views views-info"><strong><%= college.views %></strong> views</p></li>
		</ul>
	</div>
</div>

app/views/shared/_dashnavigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path,class:"navbar-brand" do %>
		<h1><%= image_tag "thumbnail"%></h1>
      <% end %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
		<div class="top-search">
			<%=form_tag(result_path,method: :get,class:"navbar-form navbar-right") do%>
				<%=text_field_tag :search,params[:search],class:"form-control",placeholder:"Search.."%>
				<%=submit_tag(value="")%>
			<% end%>
		</div> 
		<div class="header-top-right">
			<div class="file" id="upload-btn">
				<a href="#small-dialog9" class="play-icon popup-with-zoom-anim">Upload</a>
			</div>	
			<div id="small-dialog9" class="mfp-hide">
				<h3>New Upload</h3> 
				<div class="uploadlinks">
					<%= link_to "Institute",new_college_path,data: { no_turbolink: true },class:"btn btn-primary"%>
					<%= link_to "Subject",new_subject_path,data: { no_turbolink: true },class:"btn btn-success"%>
					<%= link_to "Assignment", new_assignment_path,data: { no_turbolink: true },class:"btn btn-info"%>
					<%= link_to "Practical", new_practical_path,data: { no_turbolink: true },class:"btn btn-warning"%>
					<%= link_to "Paper", new_qpaper_path,data: { no_turbolink: true },class:"btn btn-danger"%>
					<%= link_to "Notes", new_examnote_path,data: { no_turbolink: true },class:"btn btn-primary"%>
					<br><br><br>
				</div>
				<div class="clearfix"> </div>
			</div>
			<div class="signin">
				<% if user_signed_in? %>
					<% if current_user.avatar.url != "/avatars/original/missing.png" %>
						<%= link_to (image_tag current_user.avatar.url(:small),class:"navbarprofilepic"),current_user,id:"publishinghouselink"%>
					<% else%>
						<%= link_to (image_tag "customprofile",class:"navbarprofilepic"),current_user,id:"publishinghouselink"%>
					<%end %>
				<% else%>
					<a href="#small-dialog2" class="play-icon popup-with-zoom-anim">Sign In</a>
				<% end %>
				<!-- pop-up-box -->
				<!--//pop-up-box -->
				<div id="small-dialog2" class="mfp-hide">
					<h3>Sign In</h3> 
					<small>Join BitNotes Community to dive in to Resource Bucket!</small>
					<div class="social-sits">
						<div class="facebook-button">
							<%=link_to "Connect with Facebook","/auth/facebook", id: "sign_in" %>
						</div>
						<div class="chrome-button">
							<%=link_to "Connect with Google","/auth/google_oauth2", id: "sign_in" %>
						</div>
					</div>
					<div class="clearfix"> </div>
				</div>	
				<div id="small-dialog4" class="mfp-hide">
					<h3>Feedback</h3> 
					<div class="feedback-grids">
						<div class="feedback-grid">
							<p>We are always happy to hear your queries and suggestion. Mails us <a href="mailto:cwayconnect@gmail.com">here</a> with your suggestion. We would reach you back. Thank You from Team BitNotes.</p>
						</div>
					</div>
				</div>
				<div id="small-dialog5" class="mfp-hide">
					<h3>Help</h3> 
						<div class="help-grid">
							<p>Team BitNote is Happy to Help you. Below are some FAQ. If you are not satisfied with FAQ, drop a mail <a href="mailto:cwayconnect@gmail.com">here</a>, Customer Support Team would reach you back. Have Happy time BitNoting.</p>
						</div>
						<div class="help-grids">
							<div class="help-button-bottom">
								<p><a href="#small-dialog4" class="play-icon popup-with-zoom-anim">Feedback</a></p>
							</div>
							<div class="help-button-bottom">
								<p><a href="#small-dialog6" class="play-icon popup-with-zoom-anim">How to start a Publication?</a></p>
							</div>
							<div class="help-button-bottom">
								<p><a href="#small-dialog10" class="play-icon popup-with-zoom-anim">How to Upload Resource?</a></p>
							</div>
							<div class="help-button-bottom">
								<p><a href="#small-dialog11" class="play-icon popup-with-zoom-anim">How Incentive Work?</a></p>
							</div>
							<div class="help-button-bottom">
								<p><a href="/policy" class="play-icon popup-with-zoom-anim">Policy</a></p>
							</div>
							<div class="help-button-bottom">
								<p><a href="/terms" class="play-icon popup-with-zoom-anim">Terms</a></p>
							</div>
						</div>
				</div>
				<div id="small-dialog6" class="mfp-hide">
					<div class="video-information-text">
						<h4>Getting Started with Publication</h4>
						<p>Publication is way to Publish your Notes, Practical, Assignments and Papers. Below are step to setup Publication. For <a href="/try">Benefits</a> of starting Publication.</p>
						<ol>
							<li>Sign In with your Facebook or Google Account. Click on My Publication in Left Side navigation.</li>
							<li>Click on Edit Profile button, Add all the Required Fields.</li>
							<li>You are ready to Upload Assignments, Practicals, Examnotes, Papers by clicking on Upload button on Top Navigation.</li>
							<li>After successfully uploading your resource, share it with your Facebook, Google+ or Pinterest friends to earn large number of Views.</li>
							<li>Advertise your Publication to have lot of Subscribers. Lot of Subscriber is easiest way to reach lot of people and Earn lot of Incentive.</li>
						</ol>
					</div>
				</div>
				<div id="small-dialog10" class="mfp-hide">
					<div class="video-information-text">
						<h4>Uploading your first Resource..</h4>
						<p>Resources can be anything like Practicals, Assignments, Papers, Notes etc. Below is Easy step to upload resource in less than a Minute.</p>
						<ol>
							<li>Sign In with your Facebook or Google Account. Click on My Publication in Left Side navigation.</li>
							<li>Click on Edit Profile button, Add all the Required Fields.</li>
							<li>You are ready to Upload Assignments, Practicals, Notes, Papers by clicking on Upload button on Top Navigation.</li>
							<li>Fill the Form of respective Resources as specified. Add images through upload field provided. Submit the Form.</li>
							<li>Images would be Uploaded and Form would get submitted. You would be redirected on Resource page. Yay! You have done it. Share it to earn Subsciber and Incentive.</li>
						</ol>
					</div>
				</div>
				<div id="small-dialog11" class="mfp-hide">
					<div class="video-information-text">
						<h4>How Incentive Works?</h4>
						<p>Incentive is nothing but money paid By BitNotes to Publication/Creator as per views count and Advertisement money earned through respective resource.<strong> Currently Monetization Model is Under Development Stage</strong>, you would be notified about when we will start to provide incentive to Publication.<strong> Publications can build there subscriber and Audience till we complete testing of Monetization Model.</strong></p>
						<ol>
							<li>We would earn Money through Affiliate Advertising on our Site with Google AdSense, Amazon Associate Program.</li>
							<li>Money earned through each resource uploaded would be tracked.</li>
							<li>Publication would get All Statistics about Views and Earned Incentive. Large part of money earned through advertising on your resource would be Given to Publication.</li>
							<li>Little part of Advertising Money would be kept for Building BitNotes Platform and Keeping Server of BitNotes running. This money helps us provide you Free Services.</li>
						</ol>
					</div>
				</div>
				<script>
					$(document).ready(function() {
						$('.popup-with-zoom-anim').magnificPopup({
							type: 'inline',
							fixedContentPos: false,
							fixedBgPos: true,
							overflowY: 'auto',
							closeBtnInside: true,
							preloader: false,
							midClick: true,
							removalDelay: 300,
							mainClass: 'my-mfp-zoom-in'
						});																
					});
				</script>	
			</div>
			<div class="signin">
				<% if user_signed_in? %>
					<%= link_to "Sign Out",signout_path %>
				<% end %>
			</div>
			<div class="clearfix"> </div>
		</div>
    </div>
	<div class="clearfix"> </div>
  </div>
</nav>
    <div class="col-sm-3 col-md-2 sidebar">
		<div class="top-navigation">
			<div class="t-menu">MENU</div>
			<div class="t-img">
				<span class="glyphicon glyphicon-align-justify"></span>
			</div>
			<div class="clearfix"></div>
		</div>
			<div class="drop-navigation drop-navigation">
			  <ul class="nav nav-sidebar">
			   	<div id="subscription_content">
				  	<ul id="subscription">
				  		<li>
				  		<% if @user.avatar.url != "/avatars/original/missing.png" %> 
							<%= link_to image_tag(@user.avatar.url(:small),alt: @user.phname,class:"dashboardProfileImage"),@user,class:"dashProImage"%>
						<% else %>
							<%= link_to (image_tag "customprofile",class:"dashboardProfileImage"),@user%>
						<% end %>
						</li>
						<li><%=link_to @user.phname,@user,class:"dashProName"%></li>
						<li class="dashBalance">Balance: <span class="glyphicon glyphicon-usd"></span>0</li>
				  	</ul>
				</div>

				<hr>
			  	<% if current_user %>
				  	<li><%=active_link_to current_user,:active=> :exclusive,class:"user-icon" do %>
			  			<span class="glyphicon glyphicon-home" aria-hidden="left-align"></span> My Publication
			  		<% end %>
			  		</li>
			  		<li><%=active_link_to "#",:active=> :exclusive,class:"user-icon" do %>
			  			<span class="glyphicon glyphicon-usd" aria-hidden="left-align"></span> Payment Gateway.
			  		<% end %>
			  		</li>
				<% end %>
				<hr>
			  	<li><%=active_link_to user_dashboard_path(id: @user.id),:active=> :exclusive,class:"user-icon" do %>
			  			<span class="glyphicon glyphicon-credit-card" aria-hidden="true"></span> Practicals Stats
			  		<% end %>
			  	</li>
			  	<li><%=active_link_to user_dashboard_assignments_path(id: @user.id),class:"sub-icon" do %>
			  			<span class="glyphicon glyphicon-book" aria-hidden="true"></span> Assignments Stats
			  		<% end %>
			  	</li>
				<li><%=active_link_to user_dashboard_qpapers_path(id: @user.id),class:"song-icon" do %>
					<span class="glyphicon glyphicon-file" aria-hidden="true"></span> Papers Stats
					<% end %>
				</li>
				<li><%=active_link_to user_dashboard_examnotes_path(id: @user.id),class:"sub-icon" do %>
					<span class="glyphicon glyphicon-level-up" aria-hidden="true"></span> Notes Stats
					<% end %>
				</li>
				<hr>
				<li><%=active_link_to user_dashboard_colleges_path(id: @user.id),class:"song-icon" do %>
			  			<span class="glyphicon glyphicon-education" aria-hidden="true"></span> Institutes Stats
			  		<% end %>
			  	</li>
			  	<li><%=active_link_to user_dashboard_subjects_path(id: @user.id),class:"news-icon" do %>
			  			<span class="glyphicon glyphicon-wrench" aria-hidden="true"></span> Subjects Stats
			  		<% end %>
			  	</li>
			  </ul>
			   
			  <!-- script-for-menu -->
					<script>
						$( ".top-navigation" ).click(function() {
						$( ".drop-navigation" ).slideToggle( 300, function() {
						// Animation complete.
						});
						});
					</script>
			</div>
        </div>

app/views/shared/_examnotesuggestion.html.erb
<div class="single-right-grids">
	<div class="col-md-4 single-right-grid-left">
		<% if examnote.eimages.count > 0 %>
			<%= link_to image_tag(examnote.eimages.first.image.url(:small),alt: examnote.topic),examnote %>
		<% else %>
			<%= link_to image_tag("defaultcoverimage",alt: examnote.topic),examnote %>
		<%end%>
	</div>
	<div class="col-md-8 single-right-grid-right">
		<p class="wrap" title="<%=examnote.topic%>"><%= link_to examnote.topic,examnote,class:"title"%></p>
		<p class="author"><%= link_to examnote.user.phname,  controller:"users",action:"show",id:examnote.user_id,class:"author"%></p>
		<p class="views"><%=examnote.views %> views</p>
	</div>
	<div class="clearfix"> </div>
</div>

app/views/shared/_formnavigation.html.erb
 <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
         <%= link_to root_path,class:"navbar-brand" do %>
			<h1><%= image_tag "logo"%></h1>
	     <% end %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
			<div class="top-search">
					<%=form_tag(result_path,method: :get,class:"navbar-form navbar-right") do%>
						<%=text_field_tag :search,params[:search],class:"form-control",placeholder:"Search.."%>
						<%=submit_tag(value="")%>
					<% end%>
				</div> 
			<div class="header-top-right">
					<div class="file" id="upload-btn">
						<a href="#small-dialog9" class="play-icon popup-with-zoom-anim">Upload</a>
					</div>	
					<div id="small-dialog9" class="mfp-hide">
						<h3>New Upload</h3> 
						<div class="uploadlinks">
							<%= link_to "Institute",new_college_path,data: { no_turbolink: true },class:"btn btn-primary"%>
							<%= link_to "Subject",new_subject_path,data: { no_turbolink: true },class:"btn btn-success"%>
							<%= link_to "Assignment", new_assignment_path,data: { no_turbolink: true },class:"btn btn-info"%>
							<%= link_to "Practical", new_practical_path,data: { no_turbolink: true },class:"btn btn-warning"%>
							<%= link_to "Paper", new_qpaper_path,data: { no_turbolink: true },class:"btn btn-danger"%>
							<%= link_to "Notes", new_examnote_path,data: { no_turbolink: true },class:"btn btn-primary"%>
							<br><br><br>
						</div>
						<div class="clearfix"> </div>
					</div>	
					<div class="signin">
						<% if user_signed_in? %>
							<% if current_user.avatar.url != "/avatars/original/missing.png" %>
								<%= link_to (image_tag current_user.avatar.url(:small),class:"navbarprofilepic"),current_user,id:"publishinghouselink"%>
							<% else%>
								<%= link_to (image_tag "customprofile",class:"navbarprofilepic"),current_user,id:"publishinghouselink" %>
							<%end %>
						<% else%>
							<a href="#small-dialog2" class="play-icon popup-with-zoom-anim">Sign In</a>
						<% end %>
						<div id="small-dialog2" class="mfp-hide">
							<h3>Create Account</h3> 
							<small>Join BitNotes Community to dive in to Resource Bucket!</small>
							<div class="social-sits">
								<div class="facebook-button">
									<%=link_to "Connect with Facebook","/auth/facebook", id: "sign_in" %>
								</div>
								<div class="chrome-button">
									<%=link_to "Connect with Google","/auth/google_oauth2", id: "sign_in" %>
								</div>
							</div>
							<div class="clearfix"> </div>
						</div>
					</div>	
					<div id="small-dialog4" class="mfp-hide">
						<h3>Feedback</h3> 
						<div class="feedback-grids">
							<div class="feedback-grid">
								<p>We are always happy to hear your queries and suggestion. Mails us <a href="mailto:cwayconnect@gmail.com">here</a> with your suggestion. We would reach you back. Thank You from Team BitNotes.</p>
							</div>
						</div>
					</div>
					<div id="small-dialog5" class="mfp-hide">
						<h3>Help</h3> 
							<div class="help-grid">
								<p>Team BitNote is Happy to Help you. Below are some FAQ. If you are not satisfied with FAQ, drop a mail <a href="mailto:cwayconnect@gmail.com">here</a>, Customer Support Team would reach you back. Have Happy time BitNoting.</p>
							</div>
							<div class="help-grids">
								<div class="help-button-bottom">
									<p><a href="#small-dialog4" class="play-icon popup-with-zoom-anim">Feedback</a></p>
								</div>
								<div class="help-button-bottom">
									<p><a href="#small-dialog6" class="play-icon popup-with-zoom-anim">How to start a Publication?</a></p>
								</div>
								<div class="help-button-bottom">
									<p><a href="#small-dialog10" class="play-icon popup-with-zoom-anim">How to Upload Resource?</a></p>
								</div>
								<div class="help-button-bottom">
									<p><a href="#small-dialog11" class="play-icon popup-with-zoom-anim">How Incentive Work?</a></p>
								</div>
								<div class="help-button-bottom">
									<p><a href="/policy">Policy</a></p>
								</div>
								<div class="help-button-bottom">
									<p><a href="/terms">Terms</a></p>
								</div>
							</div>
					</div>
					<div id="small-dialog6" class="mfp-hide">
						<div class="video-information-text">
							<h4>Getting Started with Publication</h4>
							<p>Publication is way to Publish your Notes, Practical, Assignments and Papers. Below are step to setup Publication. For <a href="/try">Benefits</a> of starting Publication.</p>
							<ol>
								<li>Sign In with your Facebook or Google Account. Click on My Publication in Left Side navigation.</li>
								<li>Click on Edit Profile button, Add all the Required Fields.</li>
								<li>You are ready to Upload Assignments, Practicals, Examnotes, Papers by clicking on Upload button on Top Navigation.</li>
								<li>After successfully uploading your resource, share it with your Facebook, Google+ or Pinterest friends to earn large number of Views.</li>
								<li>Advertise your Publication to have lot of Subscribers. Lot of Subscriber is easiest way to reach lot of people and Earn lot of Incentive.</li>
							</ol>
						</div>
					</div>
					<div id="small-dialog10" class="mfp-hide">
						<div class="video-information-text">
							<h4>Uploading your first Resource..</h4>
							<p>Resources can be anything like Practicals, Assignments, Papers, Notes etc. Below is Easy step to upload resource in less than a Minute.</p>
							<ol>
								<li>Sign In with your Facebook or Google Account. Click on My Publication in Left Side navigation.</li>
								<li>Click on Edit Profile button, Add all the Required Fields.</li>
								<li>You are ready to Upload Assignments, Practicals, Notes, Papers by clicking on Upload button on Top Navigation.</li>
								<li>Fill the Form of respective Resources as specified. Add images through upload field provided. Submit the Form.</li>
								<li>Images would be Uploaded and Form would get submitted. You would be redirected on Resource page. Yay! You have done it. Share it to earn Subsciber and Incentive.</li>
							</ol>
						</div>
					</div>
					<div id="small-dialog11" class="mfp-hide">
						<div class="video-information-text">
							<h4>How Incentive Works?</h4>
							<p>Incentive is nothing but money paid By BitNotes to Publication/Creator as per views count and Advertisement money earned through respective resource.<strong> Currently Monetization Model is Under Development Stage</strong>, you would be notified about when we will start to provide incentive to Publication.<strong> Publications can build there subscriber and Audience till we complete testing of Monetization Model</strong></p>
							<ol>
								<li>We would earn Money through Affiliate Advertising on our Site with Google AdSense, Amazon Associate Program.</li>
								<li>Money earned through each resource uploaded would be tracked.</li>
								<li>Publication would get All Statistics about Views and Earned Incentive.Large part of money earned through advertising on your resource would be Given to Publication.</li>
								<li>Little part of Advertising Money would be kept for Building BitNotes Platform and Keeping Server of BitNotes running. This money would helps us provide you Free Services.</li>
							</ol>
						</div>
					</div>
					<script>
						$(document).ready(function() {
							$('.popup-with-zoom-anim').magnificPopup({
								type: 'inline',
								fixedContentPos: false,
								fixedBgPos: true,
								overflowY: 'auto',
								closeBtnInside: true,
								preloader: false,
								midClick: true,
								removalDelay: 300,
								mainClass: 'my-mfp-zoom-in'
							});																
						});
					</script>					
				<div class="signin">
					<% if user_signed_in? %>
						<%= link_to "Sign Out",signout_path%>
					<% end %>
				</div>
				<div class="clearfix"> </div>
			</div>
        </div>
		<div class="clearfix"> </div>
      </div>
    </nav>

app/views/shared/_revenuehitsadv.html.erb
<script data-cfasync="false" type="text/javascript" src="//clksite.com/adServe/banners?tid=158538_279016_0"></script>