config/routes.rb
Rails.application.routes.draw do
  
  constraints(:host => /www.bitnotes.in/) do
    match "/(*path)" => redirect {|params, req| "http://bitnotes.in/#{params[:path]}"},  via: [:get, :post]
  end
  constraints(:host => /bitnotes.tk/) do
    match "/(*path)" => redirect {|params, req| "http://bitnotes.in/#{params[:path]}"},  via: [:get, :post]
  end
/ Root path /
 root "abouts#index"

  get '/privacy'=>'abouts#privacy',as:"privacy"
  get '/about'=>'abouts#about', as: "about"
  get '/terms'=>'abouts#terms', as:"terms"
  get '/creators'=>'abouts#creators', as:"creators"
  get '/copyright'=>'abouts#copyright', as:"copyright"
  get '/try'=>'abouts#try', as:"try"
  get '/lang'=>'abouts#language',as:"language"
  get '/team'=>'abouts#team',as:"team"
  get '/result'=>'abouts#result',as:"result"
  get '/spams/add'=>'spams#add',as:'add_spam'
  get 'practicals/:id/destroyimage'=>"practicals#destroyimage",as:"destroypimage"
  get 'assignments/:id/destroyimage'=>"assignments#destroyimage",as:"destroyaimage"
  get 'colleges/:id/destroyimage'=>"colleges#destroyimage",as:"destroycimage"
  get 'qpapers/:id/destroyimage'=>"qpapers#destroyimage",as:"destroyqimage"
  get 'examnotes/:id/destroyimage'=>"examnotes#destroyimage",as:"destroyeimage"
  get 'subjects/:id/destroyimage'=>"subjects#destroyimage",as:"destroysimage"
  get 'users/:id/dashboard'=>"users#dashboard",as:"user_dashboard"
  get 'users/:id/dashboard/assignments'=>"users#dashassignments",as:"user_dashboard_assignments"
  get 'users/:id/dashboard/examnotes'=>"users#dashexamnotes",as:"user_dashboard_examnotes"
  get 'users/:id/dashboard/qpapers'=>"users#dashqpapers",as:"user_dashboard_qpapers"
  get 'users/:id/dashboard/subjects'=>"users#dashsubjects",as:"user_dashboard_subjects"
  get 'users/:id/dashboard/colleges'=>"users#dashcolleges",as:"user_dashboard_colleges"
  get 'loadmorepracticals'=>'practicals#loadmore',as:"loadmorepracticals"
  get 'loadmoreassignments'=>'assignments#loadmore',as:"loadmoreassignments"
  get 'loadmoreexamnotes'=>'examnotes#loadmore',as:"loadmoreexamnotes"
  get 'loadmoreqpapers'=>'qpapers#loadmore',as:"loadmoreqpapers"
  get 'loadmoresubjects'=>'subjects#loadmore',as:"loadmoresubjects"
  get 'loadmorecolleges'=>'colleges#loadmore',as:"loadmorecolleges"

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  resources :sessions, only: [:create, :destroy]

/ Resources /

  resources :users
  resources :relationships, only:[:create,:destroy]

  resources :abouts
  
  resources :practicals do
    member do
      put "like"=>"practicals#upvote"
      put "dislike"=>"practicals#downvote"
    end
  end
  resources :assignments do
    member do
      put "like"=>"assignments#upvote"
      put "dislike"=>"assignments#downvote"
    end
  end
  resources :examnotes do
    member do
      put "like"=>"examnotes#upvote"
      put "dislike"=>"examnotes#downvote"
    end
  end
  resources :qpapers do
    member do
      put "like"=>"qpapers#upvote"
      put "dislike"=>"qpapers#downvote"
    end
  end
  resources :subjects do
    member do
      put "like"=>"subjects#upvote"
      put "dislike"=>"subjects#downvote"
    end
  end
  resources :colleges do
    member do
      put "like"=>"colleges#upvote"
      put "dislike"=>"colleges#downvote"
    end
  end
  resources :requests do
    member do
      put "like"=>"requests#upvote"
    end
  end


  namespace :v1 do
    resources :practicals do
      member do
        put "like"=>"practicals#upvote"
        put "dislike"=>"practicals#downvote"
      end
    end
    resources :assignments do
      member do
        put "like"=>"assignments#upvote"
        put "dislike"=>"assignments#downvote"
      end
    end
    resources :colleges do
      member do
        put "like"=>"practicals#upvote"
        put "dislike"=>"practicals#downvote"
      end
    end
    resources :examnotes do
      member do
        put "like"=>"examnotes#upvote"
        put "dislike"=>"examnotes#downvote"
      end
    end
    resources :qpapers do
      member do
        put "like"=>"qpapers#upvote"
        put "dislike"=>"qpapers#downvote"
      end
    end
    resources :subjects do
      member do
        put "like"=>"subjects#upvote"
        put "dislike"=>"subjects#downvote"
      end
    end
    resources :users,only: [:show]
    resources :abouts,only: [:index]
    get '/result'=>'abouts#result',as:"result"
    post '/users/user_oauth' => 'users/user_oauth',as: "user_oauth"
  end

end

app/models/practical.rb
class Practical < ActiveRecord::Base
	is_impressionable :counter_cache => true, :column_name => :views, :unique => :all
	searchkick	
	acts_as_votable
	belongs_to :user
	belongs_to :college
	belongs_to :subject
	has_many :pimages
	accepts_nested_attributes_for :pimages, reject_if: :all_blank, allow_destroy: true

	scope :recent,->{all.order("created_at DESC")}

	validates :title, presence: true,length:{minimum: 5}
	validates :aim, presence: true,length:{minimum: 10}
	validates :college_id, presence: true
	validates :subject_id, presence: true
	validates :description, presence: true, length:{minimum: 20}
end

app/controllers/practicals_controller.rb
class PracticalsController < ApplicationController

	impressionist actions: [:show]
	before_action :get_practical, only: [:show,:update,:edit,:destroy,:upvote,:downvote,:destroyimage]
	before_action :authenticate_user!,only:[:edit,:new,:create,:update,:destroy]

	def index
		@practicalpageindex = 1
		if current_user && current_user.college_id.present?
			@rpracticals = Practical.where(college_id: current_user.college_id).order("created_at DESC").limit(12)
			@recentPracticals = Practical.where.not(college_id: current_user.college_id).order("created_at DESC").limit(12)
		else
			@recentPracticals = Practical.recent.limit(12);
		end
	end

	def show
		@recentAssignments = Assignment.recent.limit(4)
		@recentPracticals = Practical.recent.limit(4)
		@recentQpapers = Qpaper.recent.limit(4)
		@recentExamnotes = Examnote.recent.limit(4)
	end

	def new
		@practical = Practical.new
		@subject = Subject.new
		@college = College.new
		render layout: "form"
	end

	def create
		@practical = Practical.new(practical_params)
		@practical.user_id = current_user.id

		respond_to do |format|
			if @practical.save
				fomat.html{redirect_to @practical,notice: "Successfully created your Practical!"}
				format.js
			else
				format.html {render layout:"form",action:"new"}
				format.js
			end
		end

		if @practical.save
			redirect_to @practical,notice: "Successfully created your Practical!"
		else
			render layout:"form",action:"new"
		end
	end

	def edit
		if session[:user_id] == @practical.user_id
			@check = 1
			render layout: "form"
		else
			redirect_to root_path,notice:"Gotcha!, You don't have access to edit this Practical."
		end
	end

	def update
		if session[:user_id] == @practical.user_id
			if @practical.update(practical_params)
				redirect_to @practical,notice: "Successfully Updated your Practical"
			else
				render action:"edit",layout:"form"
			end
		else
			redirect_to root_path,notice:"Gotcha!, You don't have access to edit this Practical."
		end
	end

	def destroy
		if session[:user_id] == @practical.user_id
			@practical.destroy
			redirect_to root_path,notice:"Successfully Removed your Practical"
		else
			redirect_to root_path,notice:"Gotcha!, You don't have right to delete this Practical"
		end
	end

	def upvote
		@practical.upvote_by current_user
		@flag = 0 unless current_user
		respond_to do |format|
			format.html{redirect_to :back}
			format.js
		end
	end

	def downvote
		@practical.downvote_by current_user
		@flag = 0 unless current_user
		respond_to do |format|
			format.html{redirect_to :back}
			format.js
		end
	end

	def destroyimage
		@pimage = @practical.pimages.find(params[:imageid])
		@pimage.destroy
		redirect_to :back
	end

	def loadmore
		@practicals = Practical.all.order("created_at DESC").paginate(page: params[:page],per_page: 4)
		@practicalpageindex = params[:page].to_i;
		respond_to do |format|
			format.html{redirect_to :back}
			format.js
		end
	end
	private
		/ Strong Params for Rails 4+  /
		def practical_params
			params.require(:practical).permit(:title,:aim,:description,:subject_id,:college_id,pimages_attributes: [:id,:image,:_destroy])
		end

		/ Get Practical for above action /
		def get_practical
			@practical = Practical.find(params[:id])
		end
end

app/controllers/v1/practicals_controller.rb
module V1
	class PracticalsController < ApiController
		before_action :get_practical, only:[:show,:upvote,:downvote]
		before_action :get_current_user,only:[:upvote,:downvote]
		skip_before_filter :verify_authenticity_token

		def index
			@practicals = Practical.recent.limit(12)
			render json: @practicals.as_json( include: { user: { only: [:phname] }, pimages: { methods: [:image_url], only:[] } } ),status: :ok
		end


		def show
			render json: @practical.as_json( include: { user: { only: [:phname] }, pimages: { methods: [:image_url], only:[] } } ),status: :ok
		end

		def upvote
			@practical.upvote_by current_user
			render status: :ok, json:{
				votes: @practical.cached_votes_up
			}
		end

		def downvote
			@practical.downvote_by current_user
			render status: :ok, json:{
				votes: @practical.cached_votes_up
			}
		end

		private

			def get_practical
				@practical = Practical.find(params[:id])
			end

			def get_current_user
				current_user = User.find(params[:user_id])
			end
	end
end

app/helpers/practicals_helper.rb
module PracticalsHelper
end

app/views/practicals/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
    /**
     *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
     *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
     */
    
    var disqus_config = function () {
        shortname = "Bitnotes"
        this.page.url = '<%= url_for([@practical,{only_path: false}]) %>';  // Replace PAGE_URL with your page's canonical URL variable
        this.page.identifier = <%= "practicals/#{@practical.id}"%>; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    
    (function() {  // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        
        s.src = '//bitnotes.disqus.com/embed.js';
        
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/practicals/_fbshare.html.erb
<script>
document.getElementById('shareBtn').onclick = function() {
  FB.ui({
    method: 'share',
    display: 'popup',
    href: '<%= url_for([@practical,{only_path: false} ]) %>',
  }, function(response){});
}
</script>

app/views/practicals/_form.html.erb
<div class='form-container'>
	<%= simple_form_for(@practical,html:{multipart: true}) do |f|%>

		<div class='form-item'>
			<div class='data-header'>
				<span class='header-name'>Title:</span>
			</div>
			<div class='form-data'>
				<%= f.input :title,label: false,placeholder:"What is your Practical About?"%>	
			</div>
		</div>
		<div class='form-item'>
			<div class='data-header'>
				<span class='header-name'>Aim:</span>
			</div>
			<div class='form-data'>
				<%=f.input :aim, label: false, placeholder: "What is Aim of the Practical?"	%>
			</div>
		</div>
		<div class='form-item'>
			<div class='data-header'>
				<span class='header-name'>Subject:</span>
				<span class="header-tip">If Subject not Found,add Subject <%= link_to "here",new_subject_path %></span>
			</div>
			<div class='form-data'>
				<%=f.input :subject_id,collection: Subject.all.order("name ASC"),prompt: "Choose Subject of Practical",label:false	%>
			</div>
		</div>
		<div class='form-item'>
			<div class='data-header'>
				<span class='header-name'>College:</span>
				<span class='header-tip'>If Institute not Found,add Your Institute <%=link_to "here",new_college_path %></span>
			</div>
			<div class='form-data'>
				<%=f.input :college_id,collection: College.all.order("name ASC"),label:"Institute",prompt:"Choose Institute related to Practical",label: false	%>
			</div>
		</div>
		<div class='form-item'>
			<div class='data-header'>
				<span class='header-name'>Description:</span>
				<span class='header-tip'>Describe above Practical</span>
			</div>
			<div class='form-data'>
				<%=f.input :description, label: false, placeholder:"Describe your Practical"	%>
			</div>
		</div>
		<div class='form-item'>
			<div class='form-data'>
				<div id='image-preview-box'>	
				<% if @check == 1 %>
					<% if @practical.pimages.count > 0%>
					
						<% @practical.pimages.each do |pimage| %>

							<div class="image-preview" style="background: url(<%=pimage.image.url(:small) %>) no-repeat; background-size: 150px 200px;  ">
								<!--  Ajax call and Jquery remove function for destroyimage_path -->
								<%= link_to destroypimage_path(id: @practical.id,imageid: pimage.id),remote: true do%>
										<span class="delete-image">
											<svg fill="#0288d1" height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg">					    <path d="M15 16h4v2h-4zm0-8h7v2h-7zm0 4h6v2h-6zM3 18c0 1.1.9 2 2 2h6c1.1 0 2-.9 2-2V8H3v10zM14 5h-3l-1-1H6L5 5H2v2h12z"></path><path d="M0 0h24v24H0z" fill="none"></path>					
											</svg>
										</span>
								<% end %>
								

								<input type="file" name="practical[pimages_attributes][<%= pimage.id %>][image]" style="display: none">
							</div>
				
						<% end%>
					<% end %>							
				<% end %>
				</div>
			</div>
			<div class='data-header'>
				<span id='add-image' onclick='addImage("practical","pimages")' title="Add Image">
					<svg fill="#2196F3" height="48" viewBox="0 0 24 24" width="48" xmlns="http://www.w3.org/2000/svg">
					    <circle cx="12" cy="12" r="3.2"/>
					    <path d="M9 2L7.17 4H4c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2h-3.17L15 2H9zm3 15c-2.76 0-5-2.24-5-5s2.24-5 5-5 5 2.24 5 5-2.24 5-5 5z"/>
					    <path d="M0 0h24v24H0z" fill="none"/>
					</svg>
				</span>
			</div>

		</div>
		<div class='form-actions'>
			<%=f.submit class:"btn btn-primary form-actions-btn form-submit" %>
			<%= link_to :back do %>  
				<span class="btn btn-primary form-actions-btn form-cancel">Cancel</span>
			<% end %>
		</div>
		
	<% end %>
</div>

app/views/practicals/downvote.js.erb
var alert = $('<div class="alert alert-warning alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><h4>Sign In before you like the Post</h4></div>');
<% if @flag == 0 %>
	$(".show-top-grids").prepend(alert);
<% else %>
	$("#dislikebtn").hide();
	$("#likebtn").fadeIn();
	$("#likebtn").find(".likecount").text(<%= @practical.get_upvotes.size %>);
<% end %>

app/views/practicals/edit.html.erb
<% title "Edit Practical" %>
<div class="upload">
	<!-- container -->
	<div class="container">
		<div class="upload-grids">
			<div>
				<% if @practical.errors.any? %>
					<div class="alert alert-danger alert-dismissible" role="alert">
					   	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true	">&times;</span></button>
						<h2><%= pluralize(@practical.errors.count, "Error")%> prevented this practical from saving</h2>
						<ul>
							<% @practical.errors.full_messages.each do |msg| %>
								<li><%= msg%></li>
							<% end%>
						</ul>
					</div>
				<% end %>
 			</div>

			<%= render "form" %>

			<%= render "shared/help" %>	
		</div>
	</div>
	<!-- //container -->
</div>

app/views/practicals/index.html.erb
<% title "Trending Practicals" %>
<% keywords "Practicals, Free, BitNotes, Education, Sharing, Caring, Earn, Learn" %>
<% description " Free Trending Practicals from BitNotes" %>
<% author "BitNotes" %>
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
	<div class="main-grids">
		<div class="recommended">
			<div class="recommended-grids">
				<%=  render "shared/adsense" %>
				<br>
	<% if current_user && current_user.college_id.present? %>
				<div class="recommended-info">
					<h3>Recommended</h3>
				</div>
				<% @rpracticals.each do |practical| %>
					<%= render partial:"shared/practical", locals:{practical: practical} %>
				<% end %>
				<div class="clearfix"> </div>
			</div>
		</div>
		<hr>
		<div class="recommended">
			<div class="recommended-grids">
	<% end %>
				<div class="recommended-info">
					<h3>Practicals</h3>
				</div>
				<% @recentPracticals.each do |practical| %>
					<%= render partial: "shared/practical", locals:{practical: practical} %>
				<% end %>
				<div class="clearfix"> </div>
			</div>
		</div>
		<div class="loadmorepracticaldiv">
			<p class="loadmoregif loadmoreimage"><%=image_tag "loadmore" %></p>
			<%= link_to "Load More",loadmorepracticals_path(page: @practicalpageindex+1),remote: true,class:"loadmorebtn" %>
		</div>
	</div>

	<%= render "shared/advfooter" %>

app/views/practicals/loadmore.js.erb
$(document).ready(function(){
	<% unless @practicals.empty? %>
		var practicals = $('<div class="recommended"><div class="recommended-grids"><% @practicals.each do |practical| %>'+'<%= j render partial: "shared/practical", locals: {practical: practical} %>' + '<% end %><div class="clearfix"> </div></div></div>');
		$('.loadmorepracticaldiv').before(practicals).fadeIn();
		$('.loadmorepracticaldiv').find('a').replaceWith('<%= link_to "Load More",loadmorepracticals_path(page: @practicalpageindex+1),remote: true,class:"loadmorebtn" %>');
	<% end %>
});

app/views/practicals/new.html.erb
<% title "New Practical" %>
<div class="upload">
	<!-- container -->
	<div class="container">
		<div class="upload-grids">
			<div>
				<% if @practical.errors.any? %>
					<div class="alert alert-danger alert-dismissible" role="alert">
					   	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true	">&times;</span></button>
						<h2><%= pluralize(@practical.errors.count, "Error")%> prevented this practical from saving</h2>
						<ul>
							<% @practical.errors.full_messages.each do |msg| %>
								<li><%= msg%></li>
							<% end%>
						</ul>
					</div>
				<% end %>
 			</div>

 			<%= render 'form' %>

 			<%= render "shared/help" %>
		</div>
	</div>
	<!-- //container -->
</div>

app/views/practicals/show.html.erb
<% title @practical.title %>
<% keywords "#{@practical.title}, #{@practical.user.phname},Practicals, Exams, BitNotes, Share, Care, Learn, Earn" %>
<% description "#{@practical.title} is practical of #{@practical.user.phname} publication" %>
<% author "#{@practical.user.phname}" %>
<% fbsharetitle "#{@practical.title}" %>
<% fbshareurl "#{url_for([@practical,{only_path: false}])}" %>
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
	<div class="show-top-grids">
		<% if flash.any? %>
			<div class="alert alert-success alert-dismissible" role="alert">
			   	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true	">&times;</span></button>
			   	<h4><%= flash[:notice]%></h4>
			</div>
		<% end %>
		<div class="col-sm-8 single-left">

			<%= render "shared/adsense" %>
			<br>
			<div class="song">
				<div class="song-info">
					<h3 title="Practical Topic"><%= @practical.title %></h3>	
				</div>
				<div class="video-grid">
          				<ul class="docs-pictures">
							<% if @practical.pimages.count > 0 %>
								<% fbshareimage "#{ @practical.pimages.first.image.url(:thumb) }" %>
								<% @practical.pimages.each do |pimage| %>
									<li><%=image_tag(pimage.image.url(:small),alt: @practical.title,class: "img-thumbnail",height:"140px",width:"140px",data:{original: pimage.image.url(:thumb)}) %></li>
								<% end %>
							<% end %>
						</ul><br>
				</div>
			</div>
			<%=javascript_include_tag "viewer",'data-turbolinks-track' => true %>
			<%=javascript_include_tag "main",'data-turbolinks-track' => true %>
			
			<div class="clearfix"> </div>
			<% @user = User.find(@practical.user_id) %>
			<div class="show-right-grids">
				<ul>
					<li>
						<% if @user.avatar.url == "/avatars/original/missing.png" %>
		                	<%= link_to image_tag("customprofile",alt:"logo",height: "50px"),controller:"users",action:"show",id: @user.id %> 
		                <%else%>
		                	<%= link_to image_tag(@user.avatar.url(:thumb),alt:"logo",height: "50px",alt:@user.phname),controller: "users",action:"show",id: @user.id %>
		                <% end %>

					</li>
					<li><%=link_to @practical.user.phname,controller:"users",action: "show",id: @practical.user_id%><br>
						<%= render partial:'shared/subscribe_form',locals:{fi: 0} if current_user %></li>
                    <br>

                    <div id="result"></div>
				</ul>
			</div>
			<div class="social_response">
				<ul>
					<li><a href="#" class="icon fb-icon" title="Share on Facebook" id="shareBtn">Facebook</a></li>
					<li><a href="https://plus.google.com/share?url={<%= url_for([@practical,{only_path: false}]) %>}" onclick="javascript:window.open(this.href,
  			'', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;" class="icon googleplus-icon" title="Share on Google Plus"></a></li>
					<li><a href="//www.reddit.com/submit"  class="icon reddit-icon" title="Share on Reddit" onclick="window.location = '//www.reddit.com/submit?url=' + encodeURIComponent(window.location); return false" target="_blank"></a>	</li>
					<li><a href="https://twitter.com/intent/tweet?text= <%="Check this "+ @practical.title + " " + url_for([@practical,{only_path: false}])%>" target="_blank" title="Share on Twitter" class="icon twitter-icon">Twitter</a></li>
					<li>

						<% if current_user %>
							<%= link_to dislike_practical_path(@practical),method: :put,class:"icon dislike",title:"Dislike this",id:"dislikebtn",style:"display:#{"none" unless current_user.liked?@practical}",remote: true do %>
								<span class="dislikecount"><strong><%= @practical.cached_votes_up %></strong></span>	
							<% end %>
							<%= link_to like_practical_path(@practical),method: :put,class:"icon like",title:"Like this", id:"likebtn",style:"display:#{"none" if current_user.liked?@practical}",remote: true do %>
								<span class="likecount"><strong><%= @practical.cached_votes_up %></strong></span>
							<% end %>
						<% else %>
							<%= link_to like_practical_path(@practical),method: :put,class:"icon like",title:"Like this", id:"likebtn",remote: true do %>
							<span class="likecount"><strong><%= @practical.cached_votes_up %></strong></span>
							<% end %>
						<%end %>
					</li>
					<li class="view" title="Views Count"><strong><%= @practical.views %> views</strong></li>
					<% if session[:user_id] && session[:user_id] == @practical.user_id %>
						<li><%=link_to "Edit",edit_practical_path(@practical),id:"edit_profile_btn" %></li>
						<li><%=link_to "Delete",@practical,method: :delete,data:{confirm:"Are you sure?"},id:"edit_profile_btn" %></li>
					<% end %>
					<% if current_user %>
						<li><%= link_to "Mark as Spam",add_spam_path(user_id: current_user.id,post_id: @practical.id,type_id: 1),id: "edit_profile_btn" %></li>
					<% end %>
				</ul>
				<%= render "fbshare" %>
			</div>
			<div class="clearfix"></div>
			<div class="published">
				<div class="load_more">	
					<ul id="myList">
						<li>
							<h4>Published on <%= @practical.created_at.strftime("%d %B %Y") %></h4>
							<p><%=simple_format(@practical.description.slice(0..30))%>
						</li>
						<li>
							<%=simple_format(@practical.description.slice(30..-1))%></p>
							<div class="load-grids">
								<div class="load-grid-info">
									<p>Category:</p>
									<p>College:</p>
									<p>Subject:</p>
								</div>
								<div class="load-grid">
									<p><%=link_to "Practical",practicals_path %></p>
									<p><%= link_to @practical.college.name, controller:"colleges",action:"show",id:@practical.college_id %></p>
									<p><%= link_to @practical.subject.name, controller:"subjects",action:"show",id:@practical.subject_id %></p>
								</div>
								<div class="clearfix"> </div>
							</div>
						</li>
					</ul>
					<button id="loadMore" title="See more details">Load more</button>
					<button id="showLess" style="display:none" title="See less details">Show less</button>
				</div>
			</div>
			<div class="all-comments">
				<div class="all-comments-info">
					<%= render "disqus" %>
				</div>
			</div>
			<br>
			<%= render "shared/advfooter" %>
			<br>
		</div>
		<div class="col-md-4 single-right">
			<div class="single-grid-right">
				<div class="single-right-grids">
					<div class="col-md-12 single-right-grid-left" style="margin: 0; padding: 0;">
						 <%= render "shared/adv" %>
					</div>
				</div>
			</div>
			<h3>Up Next</h3>
			<div class="single-grid-right">
				<% @recentPracticals.each do |practical| %>
					<%= render partial: "shared/practicalsuggestion",locals:{practical: practical} %>
				<% end %>
				<% @recentAssignments.each do |assignment| %>
					<%= render partial: "shared/assignmentsuggestion",locals:{assignment: assignment} %>
				<% end %>
				<% @recentExamnotes.each do |examnote| %>
					<%= render partial: "shared/examnotesuggestion",locals:{examnote: examnote} %>
				<% end %>
				<% @recentQpapers.each do |qpaper| %>
					<%= render partial:"shared/qpapersuggestion",locals:{qpaper: qpaper} %>
				<% end %>
			</div>
		</div>
		<div class="clearfix"> </div>
	</div>

app/views/practicals/upvote.js.erb
var alert = $('<div class="alert alert-warning alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><h4>Sign In before you like the Post</h4></div>');
<% if @flag == 0 %>
	$(".show-top-grids").prepend(alert);
<% else %>
	$(".likecount").hide().text(<%= @practical.get_upvotes.size %>).fadeIn();
<% end %>